sudo: false

language: go

go:
 - 1.6

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/kisielk/errcheck
  - go test -v
  - go vet 
  - errcheck ./...

notifications:
  email:
    - marty.schoch@gmail.com
